//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbsHaythamMagdiTask.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    public partial class Member
    {
        public Member()
        {
            this.Books = new HashSet<Book>();
        }
    
    
    //	one
        [Required]
    public int Id { get; set; } // hhh
    
    //	one
        [Required]
    public string Name { get; set; } // hhh
    
    //	one
        [Required]
    public int UserId { get; set; } // hhh
    
        public virtual ICollection<Book> Books { get; set; }
    }
}
