//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbsHaythamMagdiTask.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.UserComments = new HashSet<UserComment>();
            this.UserWithUserRoles = new HashSet<UserWithUserRole>();
        }
    
    
        [Required]
    public int Id { get; set; } // hhh
    
        [Required]
    public string FirstName { get; set; } // hhh
    
        [Required]
    public string LastName { get; set; } // hhh
    
        [Required]
    public string Email { get; set; } // hhh
    
        [Required]
    public string UserName { get; set; } // hhh
    
        [Required]
    public string Password { get; set; } // hhh
    
        [Required]
    public bool IsActive { get; set; } // hhh
    
        public virtual ICollection<UserComment> UserComments { get; set; }
        public virtual ICollection<UserWithUserRole> UserWithUserRoles { get; set; }
    }
}
