//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbsHaythamMagdiTask.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserComment
    {
    
    //	one
        [Required]
    public int Id { get; set; } // hhh
    
    //	one
        [Required]
    public int UserId { get; set; } // hhh
    
    //	one
        [Required]
    public string Comment { get; set; } // hhh
    
        public virtual User User { get; set; }
    }
}
