//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularTaskApp.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    public partial class Book
    {
        public Book()
        {
            this.Members = new HashSet<Member>();
        }
    
    
    //	one
        //[Required]
    public int Id { get; set; } // hhh
    
    //	one
        //[Required]
    public string Name { get; set; } // hhh
    
        public virtual ICollection<Member> Members { get; set; }
    }
}
