//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularTaskApp.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserRole
    {
        public UserRole()
        {
            this.UserWithUserRoles = new HashSet<UserWithUserRole>();
        }
    
    
    //	one
        //[Required]
    public int Id { get; set; } // hhh
    
    //	one
        //[Required]
    public string Name { get; set; } // hhh
    
        public virtual ICollection<UserWithUserRole> UserWithUserRoles { get; set; }
    }
}
